### ISSUE TITLE
verify_password should use constant-time equality comparison

### ISSUE THREAD

**Issue by y-a-n-n** [JaakkoL/firebase-scrypt-python#1]
Hi,

Just raising this issue because I fixed it in [firebase-scrypt-java](https://github.com/SmartMoveSystems/firebase-scrypt-java) and noticed it applies here too:

The string comparison in `verify_password` is not constant time, which introduces a security risk.

[Python reference](https://securitypitfalls.wordpress.com/2018/08/03/constant-time-compare-in-python/)

[Java reference](https://www.pixelstech.net/article/1431658986-Arrays-equals%28%29-vs-MessageDigest-isEqual%28%29)

**Comment by JaakkoL** [comment]
@y-a-n-n Thanks for the heads up!

Fixed in https://github.com/JaakkoL/firebase-scrypt-python/commit/6fc8ba099832b6a9f00b5d964c177199f12eec81
