### ISSUE TITLE
👋 Thanks: using your version, recommended an adjustment

### ISSUE THREAD

**Issue by mo9a7i** [JaakkoL/firebase-scrypt-python#3]
Hello JAakkoL

Thanks for your efforts bro, it saved me time researching

I have built a dockerized version to expose an API endpoint around your code https://github.com/6degrees/py_dockerized_scrypt_hasher
I have also created a pull request if you're interested to implement, when using parameters as part of a GET request, that adjustment is needed to avoid errors when the salt contains a - or + or any other random URL style characters that might mean something else to a base64 decoder.

Cheers.

**Comment by JaakkoL** [comment]
Discussed here: https://github.com/JaakkoL/firebase-scrypt-python/pull/2
