### ISSUE TITLE
Releasing on PyPI

### ISSUE THREAD

**Issue by nhairs** [JaakkoL/firebase-scrypt-python#4]
Hi @JaakkoL,
First of all thanks for creating this package and saving me the headache of figuring this out myself :tada:.

Rather than installing from source it would be great to be able to install this package from PyPI (think `pip install firebasescrypt`).

I'm happy to help out with this as I already have a few projects on PyPI. Probably a few ways I can help:
- General questions support
- providing a PR porting firebasescrypt to my own https://github.com/nhairs/python-package-template (which would then make it very easy test/upload etc)
- Being added/considered as a maintainer and managing uploading new versions to PyPI as needed (so that you don't have to)
  (which given the simple nature of the project wouldn't be very often).

I'll note there is a similar project already on PyPI https://pypi.org/project/pyscryptfirebase/ however this package:
1. requires OpenSSL
2. doesn't support checking passwords against a hash.

It /might/ be worth considering combining efforts with the maintainers of that package.

**Comment by JaakkoL** [comment]
Hi @nhairs!

Thanks for the suggestion. I personally have no plans in packaging this to PyPI. If you believe there would be a larger audience for it, feel free to fork the repo and publish it as a PyPI package.

**Comment by nhairs** [comment]
Per discussion I've decided to fork this in order to release it on PyPI:

- https://github.com/nhairs/firebase-scrypt-python
- https://pypi.org/project/firebase-scrypt/

**Comment by JaakkoL** [comment]
Looks neat @nhairs!
