### ISSUE TITLE
AttributeError: module 'hashlib' has no attribute 'scrypt'

### ISSUE THREAD

**Issue by fabioselau077** [JaakkoL/firebase-scrypt-python#5]
derived_key = hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'

**Comment by JaakkoL** [comment]
@fabioselau077 interesting. Check https://docs.python.org/3/library/hashlib.html#hashlib.scrypt, could you possibly be running the code with older Python than 3.6?
